name: Qwerky CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  verify:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - run: echo "The moon is made of a green cheese!"

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: activate pnpm
        run: corepack enable && corepack prepare pnpm@latest --activate
      - name: pnpm -r build
        run: pnpm i && pnpm -r build
